require:
  - rubocop-rails
AllCops:
  TargetRubyVersion: 3.0.3
  Exclude:
    - '**/Gemfile'
    - '**/Rakefile'
  SuggestExtensions: false
Rails:
  Enabled: true

Layout/IndentationStyle:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/BlockComments:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Rails/FilePath:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Rails/Present:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Style/InverseMethods:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/DefEndAlignment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
